import { PM_SHEETS } from "@/config/predictive-sheets";

export type MetricType = "LAG" | "LEAD_1" | "LEAD_2" | "ACTIVITY" | "CAPACITY" | "GUARDRAIL";
export type MetricDirection = "HIGHER_IS_BETTER" | "LOWER_IS_BETTER" | "TARGET_RANGE";
export type MetricUnit = "eur" | "count" | "ratio" | "percent";
export type MetricKind = "additive" | "rate";

export type PmCatalogMetric = {
  metric_id: string;
  category: string;
  metric_name: string;
  metric_type: MetricType;
  direction: MetricDirection;
  unit: MetricUnit;
  kind: MetricKind;
  owner: string;
  parent_metric_id: string;
  plan_source: string;
  fact_source: string;
  forecast_method: string;
  is_primary: boolean;
  /** Which detail sheet this metric belongs to */
  sheet: string;
  section: string;
  glossary: string;
  formulaHint: string;
};

/** Canonical metric dictionary — no invented plans/facts here. */
export const PM_METRIC_CATALOG: PmCatalogMetric[] = [
  // —— Marketing General ——
  {
    metric_id: "mg_revenue",
    category: "Marketing",
    metric_name: "Выручка",
    metric_type: "LAG",
    direction: "HIGHER_IS_BETTER",
    unit: "eur",
    kind: "additive",
    owner: "Маркетинг / РОП",
    parent_metric_id: "",
    plan_source: "CEO План/факт → ОБЩИЕ",
    fact_source: "Bitrix SPA Счета type/31: Оплачено + Дата завершения",
    forecast_method: "calendar_run_rate",
    is_primary: true,
    sheet: PM_SHEETS.marketingGeneral,
    section: "BUSINESS OUTCOME",
    glossary: "Оплаченная выручка за период (SPA Счета, дата завершения).",
    formulaHint: "Σ payments.amount"
  },
  {
    metric_id: "mg_payments",
    category: "Marketing",
    metric_name: "Оплаты",
    metric_type: "LEAD_1",
    direction: "HIGHER_IS_BETTER",
    unit: "count",
    kind: "additive",
    owner: "РОП",
    parent_metric_id: "mg_revenue",
    plan_source: "CEO План/факт → ОБЩИЕ",
    fact_source: "Bitrix SPA Счета type/31: Оплачено + Дата завершения",
    forecast_method: "calendar_run_rate",
    is_primary: true,
    sheet: PM_SHEETS.marketingGeneral,
    section: "BUSINESS OUTCOME",
    glossary: "Количество оплат (клиентов) за период.",
    formulaHint: "COUNT(payments)"
  },
  {
    metric_id: "mg_average_check",
    category: "Marketing",
    metric_name: "Средний чек",
    metric_type: "LEAD_1",
    direction: "HIGHER_IS_BETTER",
    unit: "eur",
    kind: "rate",
    owner: "РОП",
    parent_metric_id: "mg_revenue",
    plan_source: "CEO План/факт / DERIVED",
    fact_source: "Revenue / Payments",
    forecast_method: "rate_current",
    is_primary: true,
    sheet: PM_SHEETS.marketingGeneral,
    section: "BUSINESS OUTCOME",
    glossary: "Средний чек оплаты = Выручка / Оплаты. Не линейно экстраполируется.",
    formulaHint: "Revenue / Payments"
  },
  {
    metric_id: "mg_leads",
    category: "Marketing",
    metric_name: "Лиды",
    metric_type: "LEAD_2",
    direction: "HIGHER_IS_BETTER",
    unit: "count",
    kind: "additive",
    owner: "Маркетинг",
    parent_metric_id: "mg_qualified_leads",
    plan_source: "CEO План/факт → ОБЩИЕ",
    fact_source: "CEO План/факт / Traffic OS",
    forecast_method: "calendar_run_rate",
    is_primary: true,
    sheet: PM_SHEETS.marketingGeneral,
    section: "LEAD KPI",
    glossary: "Все входящие лиды за период.",
    formulaHint: "COUNT(leads)"
  },
  {
    metric_id: "mg_qualified_leads",
    category: "Marketing",
    metric_name: "Квалифицированные лиды",
    metric_type: "LEAD_2",
    direction: "HIGHER_IS_BETTER",
    unit: "count",
    kind: "additive",
    owner: "Маркетинг / РОП",
    parent_metric_id: "mg_invoices",
    plan_source: "CEO План/факт → ОБЩИЕ",
    fact_source: "CEO План/факт",
    forecast_method: "calendar_run_rate",
    is_primary: true,
    sheet: PM_SHEETS.marketingGeneral,
    section: "LEAD KPI",
    glossary: "Лиды, прошедшие квалификацию.",
    formulaHint: "COUNT(qualified leads)"
  },
  {
    metric_id: "mg_paid_leads",
    category: "Marketing",
    metric_name: "Платные лиды",
    metric_type: "LEAD_2",
    direction: "HIGHER_IS_BETTER",
    unit: "count",
    kind: "additive",
    owner: "Маркетинг",
    parent_metric_id: "mg_leads",
    plan_source: "CEO План/факт → Paid",
    fact_source: "Traffic OS / CEO",
    forecast_method: "calendar_run_rate",
    is_primary: false,
    sheet: PM_SHEETS.marketingGeneral,
    section: "CHANNELS",
    glossary: "Лиды из платных каналов.",
    formulaHint: "COUNT(paid leads)"
  },
  {
    metric_id: "mg_organic_leads",
    category: "Marketing",
    metric_name: "Органические лиды",
    metric_type: "LEAD_2",
    direction: "HIGHER_IS_BETTER",
    unit: "count",
    kind: "additive",
    owner: "Маркетинг",
    parent_metric_id: "mg_leads",
    plan_source: "CEO План/факт → Органика",
    fact_source: "Traffic OS / CEO",
    forecast_method: "calendar_run_rate",
    is_primary: false,
    sheet: PM_SHEETS.marketingGeneral,
    section: "CHANNELS",
    glossary: "Лиды из органических каналов.",
    formulaHint: "COUNT(organic leads)"
  },
  {
    metric_id: "mg_invoices",
    category: "Marketing",
    metric_name: "Счета",
    metric_type: "LEAD_1",
    direction: "HIGHER_IS_BETTER",
    unit: "count",
    kind: "additive",
    owner: "РОП",
    parent_metric_id: "mg_payments",
    plan_source: "CEO План/факт → ОБЩИЕ",
    fact_source: "Bitrix «Выставлен счет» + стадия Выставление счета",
    forecast_method: "calendar_run_rate",
    is_primary: true,
    sheet: PM_SHEETS.marketingGeneral,
    section: "SALES FUNNEL",
    glossary: "Количество выставленных счетов (event view).",
    formulaHint: "COUNT(invoices)"
  },
  {
    metric_id: "mg_cpl",
    category: "Marketing",
    metric_name: "CPL смешанный",
    metric_type: "GUARDRAIL",
    direction: "LOWER_IS_BETTER",
    unit: "eur",
    kind: "rate",
    owner: "Маркетинг",
    parent_metric_id: "mg_leads",
    plan_source: "CEO План/факт / DERIVED",
    fact_source: "Spend / Leads",
    forecast_method: "rate_current",
    is_primary: true,
    sheet: PM_SHEETS.marketingGeneral,
    section: "GUARDRAILS",
    glossary: "Стоимость лида. LOWER_IS_BETTER.",
    formulaHint: "Spend / Leads"
  },
  {
    metric_id: "mg_cac",
    category: "Marketing",
    metric_name: "CAC",
    metric_type: "GUARDRAIL",
    direction: "LOWER_IS_BETTER",
    unit: "eur",
    kind: "rate",
    owner: "Маркетинг",
    parent_metric_id: "mg_payments",
    plan_source: "CEO План/факт",
    fact_source: "Spend / Payments",
    forecast_method: "rate_current",
    is_primary: false,
    sheet: PM_SHEETS.marketingGeneral,
    section: "GUARDRAILS",
    glossary: "Стоимость привлечения клиента. LOWER_IS_BETTER.",
    formulaHint: "Spend / Payments"
  },
  {
    metric_id: "mg_roas",
    category: "Marketing",
    metric_name: "ROAS",
    metric_type: "GUARDRAIL",
    direction: "HIGHER_IS_BETTER",
    unit: "percent",
    kind: "rate",
    owner: "Маркетинг",
    parent_metric_id: "mg_revenue",
    plan_source: "CEO План/факт",
    fact_source: "Revenue / Spend",
    forecast_method: "rate_current",
    is_primary: false,
    sheet: PM_SHEETS.marketingGeneral,
    section: "GUARDRAILS",
    glossary: "Return on ad spend (как в CEO-таблице).",
    formulaHint: "Revenue / Spend"
  },
  {
    metric_id: "mg_budget",
    category: "Marketing",
    metric_name: "Бюджет рекламы",
    metric_type: "CAPACITY",
    direction: "HIGHER_IS_BETTER",
    unit: "eur",
    kind: "additive",
    owner: "Маркетинг",
    parent_metric_id: "mg_leads",
    plan_source: "CEO План/факт → ОБЩИЕ",
    fact_source: "CEO План/факт (Spend MTD)",
    forecast_method: "calendar_run_rate",
    is_primary: true,
    sheet: PM_SHEETS.marketingGeneral,
    section: "CAPACITY",
    glossary: "Бюджет / факт spend платного медиа.",
    formulaHint: "Σ spend"
  },

  // —— Marketing Paid ——
  {
    metric_id: "mp_revenue",
    category: "Paid",
    metric_name: "Выручка (платная)",
    metric_type: "LAG",
    direction: "HIGHER_IS_BETTER",
    unit: "eur",
    kind: "additive",
    owner: "Маркетинг",
    parent_metric_id: "",
    plan_source: "CEO План/факт → Paid",
    fact_source: "CEO / attribution",
    forecast_method: "calendar_run_rate",
    is_primary: true,
    sheet: PM_SHEETS.marketingPaid,
    section: "BUSINESS OUTCOME",
    glossary: "Выручка, атрибутированная paid-каналам.",
    formulaHint: "Σ paid attributed revenue"
  },
  {
    metric_id: "mp_payments",
    category: "Paid",
    metric_name: "Оплаты",
    metric_type: "LEAD_1",
    direction: "HIGHER_IS_BETTER",
    unit: "count",
    kind: "additive",
    owner: "Маркетинг",
    parent_metric_id: "mp_revenue",
    plan_source: "CEO План/факт → Paid",
    fact_source: "CEO / attribution",
    forecast_method: "calendar_run_rate",
    is_primary: true,
    sheet: PM_SHEETS.marketingPaid,
    section: "BUSINESS OUTCOME",
    glossary: "Оплаты из paid.",
    formulaHint: "COUNT(paid payments)"
  },
  {
    metric_id: "mp_qualified_leads",
    category: "Paid",
    metric_name: "Квал. лиды",
    metric_type: "LEAD_2",
    direction: "HIGHER_IS_BETTER",
    unit: "count",
    kind: "additive",
    owner: "Маркетинг",
    parent_metric_id: "mp_payments",
    plan_source: "CEO План/факт → Paid",
    fact_source: "CEO",
    forecast_method: "calendar_run_rate",
    is_primary: true,
    sheet: PM_SHEETS.marketingPaid,
    section: "LEAD GENERATION",
    glossary: "Квал. лиды paid.",
    formulaHint: "COUNT(paid QL)"
  },
  {
    metric_id: "mp_leads",
    category: "Paid",
    metric_name: "Лиды",
    metric_type: "LEAD_2",
    direction: "HIGHER_IS_BETTER",
    unit: "count",
    kind: "additive",
    owner: "Маркетинг",
    parent_metric_id: "mp_qualified_leads",
    plan_source: "CEO План/факт → Paid",
    fact_source: "CEO / Traffic OS",
    forecast_method: "calendar_run_rate",
    is_primary: true,
    sheet: PM_SHEETS.marketingPaid,
    section: "LEAD GENERATION",
    glossary: "Лиды paid.",
    formulaHint: "COUNT(paid leads)"
  },
  {
    metric_id: "mp_spend",
    category: "Paid",
    metric_name: "Расход",
    metric_type: "CAPACITY",
    direction: "HIGHER_IS_BETTER",
    unit: "eur",
    kind: "additive",
    owner: "Маркетинг",
    parent_metric_id: "mp_leads",
    plan_source: "CEO План/факт → Paid",
    fact_source: "СВОД day → Расход",
    forecast_method: "calendar_run_rate",
    is_primary: true,
    sheet: PM_SHEETS.marketingPaid,
    section: "CAPACITY",
    glossary: "Расход paid-медиа.",
    formulaHint: "Σ spend"
  },
  {
    metric_id: "mp_cpl",
    category: "Paid",
    metric_name: "CPL",
    metric_type: "GUARDRAIL",
    direction: "LOWER_IS_BETTER",
    unit: "eur",
    kind: "rate",
    owner: "Маркетинг",
    parent_metric_id: "mp_leads",
    plan_source: "DERIVED / CEO",
    fact_source: "Spend / Leads",
    forecast_method: "rate_current",
    is_primary: true,
    sheet: PM_SHEETS.marketingPaid,
    section: "GUARDRAILS",
    glossary: "CPL paid. LOWER_IS_BETTER.",
    formulaHint: "Spend / Leads"
  },
  {
    metric_id: "mp_cpql",
    category: "Paid",
    metric_name: "CPQL",
    metric_type: "GUARDRAIL",
    direction: "LOWER_IS_BETTER",
    unit: "eur",
    kind: "rate",
    owner: "Маркетинг",
    parent_metric_id: "mp_qualified_leads",
    plan_source: "DERIVED",
    fact_source: "Spend / QL",
    forecast_method: "rate_current",
    is_primary: false,
    sheet: PM_SHEETS.marketingPaid,
    section: "GUARDRAILS",
    glossary: "Cost per qualified lead. LOWER_IS_BETTER.",
    formulaHint: "Spend / Qualified Leads"
  },
  {
    metric_id: "mp_cac",
    category: "Paid",
    metric_name: "CAC",
    metric_type: "GUARDRAIL",
    direction: "LOWER_IS_BETTER",
    unit: "eur",
    kind: "rate",
    owner: "Маркетинг",
    parent_metric_id: "mp_payments",
    plan_source: "CEO / DERIVED",
    fact_source: "Spend / Payments",
    forecast_method: "rate_current",
    is_primary: false,
    sheet: PM_SHEETS.marketingPaid,
    section: "GUARDRAILS",
    glossary: "CAC paid.",
    formulaHint: "Spend / Payments"
  },
  {
    metric_id: "mp_roas",
    category: "Paid",
    metric_name: "ROAS",
    metric_type: "GUARDRAIL",
    direction: "HIGHER_IS_BETTER",
    unit: "percent",
    kind: "rate",
    owner: "Маркетинг",
    parent_metric_id: "mp_revenue",
    plan_source: "CEO План/факт → Paid",
    fact_source: "Revenue / Spend",
    forecast_method: "rate_current",
    is_primary: true,
    sheet: PM_SHEETS.marketingPaid,
    section: "GUARDRAILS",
    glossary: "ROAS paid.",
    formulaHint: "Revenue / Spend"
  },

  // —— Marketing Organic ——
  {
    metric_id: "mo_revenue",
    category: "Organic",
    metric_name: "Выручка (органика)",
    metric_type: "LAG",
    direction: "HIGHER_IS_BETTER",
    unit: "eur",
    kind: "additive",
    owner: "Маркетинг",
    parent_metric_id: "",
    plan_source: "CEO План/факт → Органика",
    fact_source: "CEO / attribution",
    forecast_method: "calendar_run_rate",
    is_primary: true,
    sheet: PM_SHEETS.marketingOrganic,
    section: "BUSINESS OUTCOME",
    glossary: "Выручка органики.",
    formulaHint: "Σ organic revenue"
  },
  {
    metric_id: "mo_payments",
    category: "Organic",
    metric_name: "Оплаты (органика)",
    metric_type: "LEAD_1",
    direction: "HIGHER_IS_BETTER",
    unit: "count",
    kind: "additive",
    owner: "Маркетинг",
    parent_metric_id: "mo_revenue",
    plan_source: "CEO План/факт → Органика",
    fact_source: "CEO",
    forecast_method: "calendar_run_rate",
    is_primary: true,
    sheet: PM_SHEETS.marketingOrganic,
    section: "BUSINESS OUTCOME",
    glossary: "Оплаты органики.",
    formulaHint: "COUNT(organic payments)"
  },
  {
    metric_id: "mo_qualified_leads",
    category: "Organic",
    metric_name: "Квал. лиды (органика)",
    metric_type: "LEAD_2",
    direction: "HIGHER_IS_BETTER",
    unit: "count",
    kind: "additive",
    owner: "Маркетинг",
    parent_metric_id: "mo_payments",
    plan_source: "CEO План/факт → Органика",
    fact_source: "CEO",
    forecast_method: "calendar_run_rate",
    is_primary: true,
    sheet: PM_SHEETS.marketingOrganic,
    section: "LEAD GENERATION",
    glossary: "Квал. лиды органики.",
    formulaHint: "COUNT(organic QL)"
  },
  {
    metric_id: "mo_leads",
    category: "Organic",
    metric_name: "Органические лиды",
    metric_type: "LEAD_2",
    direction: "HIGHER_IS_BETTER",
    unit: "count",
    kind: "additive",
    owner: "Маркетинг",
    parent_metric_id: "mo_qualified_leads",
    plan_source: "CEO План/факт → Органика",
    fact_source: "CEO / Traffic OS",
    forecast_method: "calendar_run_rate",
    is_primary: true,
    sheet: PM_SHEETS.marketingOrganic,
    section: "LEAD GENERATION",
    glossary: "Лиды органики.",
    formulaHint: "COUNT(organic leads)"
  },
  {
    metric_id: "mo_lead_payment_cr",
    category: "Organic",
    metric_name: "Конверсия лид → оплата",
    metric_type: "GUARDRAIL",
    direction: "HIGHER_IS_BETTER",
    unit: "percent",
    kind: "rate",
    owner: "Маркетинг / РОП",
    parent_metric_id: "mo_payments",
    plan_source: "DERIVED / CEO",
    fact_source: "Payments / Leads",
    forecast_method: "rate_current",
    is_primary: true,
    sheet: PM_SHEETS.marketingOrganic,
    section: "GUARDRAILS",
    glossary: "Конверсия лид → оплата (event). ⚠ не когорта.",
    formulaHint: "Payments / Leads"
  },

  // —— Sales General ——
  {
    metric_id: "sg_revenue",
    category: "Sales",
    metric_name: "Выручка",
    metric_type: "LAG",
    direction: "HIGHER_IS_BETTER",
    unit: "eur",
    kind: "additive",
    owner: "РОП",
    parent_metric_id: "",
    plan_source: "CEO План/факт → ОБЩИЕ",
    fact_source: "Bitrix SPA Счета type/31: Оплачено + Дата завершения",
    forecast_method: "calendar_run_rate",
    is_primary: true,
    sheet: PM_SHEETS.salesGeneral,
    section: "BUSINESS OUTCOME",
    glossary: "Оплаченная выручка отдела: SPA Счета, стадия Оплачено, дата завершения.",
    formulaHint: "Σ payments.amount"
  },
  {
    metric_id: "sg_payments",
    category: "Sales",
    metric_name: "Оплаты",
    metric_type: "LEAD_1",
    direction: "HIGHER_IS_BETTER",
    unit: "count",
    kind: "additive",
    owner: "РОП",
    parent_metric_id: "sg_revenue",
    plan_source: "CEO План/факт → ОБЩИЕ",
    fact_source: "Bitrix SPA Счета type/31: Оплачено + Дата завершения",
    forecast_method: "calendar_run_rate",
    is_primary: true,
    sheet: PM_SHEETS.salesGeneral,
    section: "BUSINESS OUTCOME",
    glossary: "Количество оплат.",
    formulaHint: "COUNT(payments)"
  },
  {
    metric_id: "sg_average_check",
    category: "Sales",
    metric_name: "Средний чек",
    metric_type: "LEAD_1",
    direction: "HIGHER_IS_BETTER",
    unit: "eur",
    kind: "rate",
    owner: "РОП",
    parent_metric_id: "sg_revenue",
    plan_source: "CEO / DERIVED",
    fact_source: "Revenue / Payments",
    forecast_method: "rate_current",
    is_primary: true,
    sheet: PM_SHEETS.salesGeneral,
    section: "BUSINESS OUTCOME",
    glossary: "Средний чек = Выручка / Оплаты.",
    formulaHint: "Revenue / Payments"
  },
  {
    metric_id: "sg_leads",
    category: "Sales",
    metric_name: "Лиды",
    metric_type: "LEAD_2",
    direction: "HIGHER_IS_BETTER",
    unit: "count",
    kind: "additive",
    owner: "РОП",
    parent_metric_id: "sg_qualified_leads",
    plan_source: "CEO План/факт",
    fact_source: "Sales OS / Bitrix",
    forecast_method: "calendar_run_rate",
    is_primary: true,
    sheet: PM_SHEETS.salesGeneral,
    section: "FUNNEL",
    glossary: "Лиды, назначенные отделу продаж.",
    formulaHint: "COUNT(leads)"
  },
  {
    metric_id: "sg_qualified_leads",
    category: "Sales",
    metric_name: "Квал. лиды",
    metric_type: "LEAD_2",
    direction: "HIGHER_IS_BETTER",
    unit: "count",
    kind: "additive",
    owner: "РОП",
    parent_metric_id: "sg_invoices",
    plan_source: "CEO План/факт",
    fact_source: "Sales OS / Bitrix",
    forecast_method: "calendar_run_rate",
    is_primary: true,
    sheet: PM_SHEETS.salesGeneral,
    section: "FUNNEL",
    glossary: "Квалифицированные лиды в CRM.",
    formulaHint: "COUNT(QL)"
  },
  {
    metric_id: "sg_invoices",
    category: "Sales",
    metric_name: "Счета",
    metric_type: "LEAD_1",
    direction: "HIGHER_IS_BETTER",
    unit: "count",
    kind: "additive",
    owner: "РОП",
    parent_metric_id: "sg_payments",
    plan_source: "CEO План/факт",
    fact_source: "Bitrix «Выставлен счет» + стадия Выставление счета",
    forecast_method: "calendar_run_rate",
    is_primary: true,
    sheet: PM_SHEETS.salesGeneral,
    section: "FUNNEL",
    glossary: "Выставленные счета (event view по дате счёта).",
    formulaHint: "COUNT(invoices)"
  },
  {
    metric_id: "sg_cr_invoice_payment",
    category: "Sales",
    metric_name: "Счёт → оплата",
    metric_type: "GUARDRAIL",
    direction: "HIGHER_IS_BETTER",
    unit: "percent",
    kind: "rate",
    owner: "РОП",
    parent_metric_id: "sg_payments",
    plan_source: "CEO План/факт (Счет в оплату)",
    fact_source: "Bitrix оплаты / счета",
    forecast_method: "rate_current",
    is_primary: true,
    sheet: PM_SHEETS.salesGeneral,
    section: "FUNNEL",
    glossary: "Конверсия счет→оплата. Стыкует счета с 150 оплатами в Н2.",
    formulaHint: "Payments / Invoices"
  }
];

export function metricsForSheet(sheet: string): PmCatalogMetric[] {
  return PM_METRIC_CATALOG.filter((m) => m.sheet === sheet);
}

export function primaryMetrics(): PmCatalogMetric[] {
  return PM_METRIC_CATALOG.filter((m) => m.is_primary);
}
